set_property SRC_FILE_INFO {cfile:/home/marion/alles/fpga_tutorial/my_first_project/constraints_1/switchToLED_neexys4DDR_constaints.xdc rfile:../../../constraints_1/switchToLED_neexys4DDR_constaints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports slideSwitch]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports led]
